config/routes.rb
Rails.application.routes.draw do
  resources :labels
  get 'sessions/new'
  get 'sessions/create'
  resources :users
  root 'tasks#index'
  resources :tasks
  resources :users
 resources :sessions
 resources :sessions, only: [:new, :create, :destroy]
 get 'signup', to: 'users#new', as: 'signup'
 get 'login', to: 'sessions#new', as: 'login'
 get 'logout', to: 'sessions#destroy', as: 'logout'
 namespace :admin do
  resources :users
 end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-success">
  <a class="navbar-brand" href="#" id="every">Everleaf</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Home', tasks_path, class:"nav-link", id:"every" %>
      </li>
      <li class="nav-item">
        <%= link_to 'New Task', new_task_path, class:"nav-link", id:"every" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="every" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sort
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Sort By Name", tasks_path(sort_by: "name"), class:'dropdown-item' %>
          <%= link_to "Sort By Date", tasks_path(sort_by: "end_date"), class:'dropdown-item' %>
          <%= link_to "Sort By Priority", tasks_path(sort_by: "prior"), class:'dropdown-item' %>
        </div>
      </li>
      </form>
      <% if current_user && current_user.user_type == "admin" %>
    <%= link_to 'Admin screen', admin_users_path, id: "every" %>
   <% end %>
   <% if current_user %>
     <li class="nav-item">
     <%= link_to 'Normal Users', users_path, id: "every" %>
     </li>
     <li class="nav-item">
     <%= link_to 'Labels', labels_path, id: "every" %>
     </li>
     <% end %>
    <% if current_user %>
       Logged in as <%= current_user.name %>.
       <%= link_to "Log Out", logout_path, class:"nav-link", id:"every" %>
     <% else %>
       <%= link_to "Sign Up", signup_path, class:"nav-link", id:"every" %> 
       <%= link_to "Log In", login_path, class:"nav-link", id:"every" %>
     <% end %>
    </ul>
  </div>
  <%= form_tag(tasks_path, :method => "get", style: "float:right;margin-right:3px", class:"form-inline") do %>
    <%= text_field_tag :term, params[:term], placeholder: "search by both name or status", class:"form-control mr-sm-2" %>
    <%= submit_tag "Search", class:"btn btn-outline-primary my-2 my-sm-0", type:"submit", id:"every" %>
  <% end %>
</nav><br/><br/>
<center>
    <%= yield %>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>